// Game parameters
export const BOARD = {
    width: 50,
    height: 50,
}
export const CELL_SIZE = 50
export const INIT_SIGHT = 5.5

// Graphic parameters
export const CELL_HIDE_DELAY = 100

// Transition timings (ms)
export const CELL_FADE_DURATION_MS = 500
export const CELL_FADE_STEP_DELAY_MS = 24
export const INTRO_REVEAL_FADE_DURATION_MS = CELL_FADE_DURATION_MS * 3
export const HERO_FADE_DURATION_MS = 1020
export const BUBBLE_FADE_DURATION_MS = 400

// Control hints — shown once, the first time the player finishes the
// intro cutscene.
export const HINT_DELAY_AFTER_INTRO_MS = 1000
export const HINT_VISIBLE_MS = 15000
export const HINT_FADE_MS = 400
export const MOVE_PAD_IDLE_PULSE_MS = 5000

// Ghost sprites: subfolder under public/images/ containing
// ghost_1.png..ghost_N.png. Keep GHOST_COUNT in sync with the
// actual number of files in that folder.
export const GHOST_FOLDER = 'ghosts'
export const GHOST_COUNT = 19

// Active wall tile set: subfolder under public/images/ containing
// wall1.png..wallN.png. Keep WALL_VARIANT_COUNT in sync with the
// actual number of files in that folder.
export const WALL_FOLDER = 'walls_straight'
export const WALL_VARIANT_COUNT = 16

// Inverted wall tiles used by the start-menu title (white bricks with
// black separators). Generated by scripts/comfyui/invert-walls or the
// Python snippet that mirrors public/images/<WALL_FOLDER>/.
export const MENU_WALL_FOLDER = 'walls_straight_inverted'
export const MENU_WALL_VARIANT_COUNT = 16

export function randomGhostImage() {
    const idx = Math.floor(Math.random() * GHOST_COUNT) + 1
    return `/images/${GHOST_FOLDER}/ghost_${idx}.png`
}

export function randomWallVariant() {
    return Math.floor(Math.random() * WALL_VARIANT_COUNT) + 1
}

export function randomMenuWallVariant() {
    return Math.floor(Math.random() * MENU_WALL_VARIANT_COUNT) + 1
}

// Debug flags
// When true, instantly fills all 4 bubble slots on mount with random messages.
// Enabled via `npm run debug` (sets VITE_DEBUG_THOUGHT_BUBBLES=1).
export const DEBUG_ALL_THOUGHT_BUBBLES = import.meta.env.VITE_DEBUG_THOUGHT_BUBBLES === '1'
